title: "Zongjiang Shang"
title_separator: "-"
name: &name "Zongjiang Shang"
description: &description "Zongjiang Shang's Academic Homepage"
url: "https://shangzongjiang.github.io"
baseurl: ""
repository: "shangzongjiang/shangzongjiang.github.io"

author:
  avatar: "szj.jpg"
  name: "Zongjiang Shang"
  bio: "Ph.D. Candidate at Zhejiang University"
  location: "Hangzhou, China"
  employer: "Zhejiang University"
  uri:
  email: "zongjiangshang@cs.zju.edu.cn"

  arxiv:
  googlescholar: "https://scholar.google.com/citations?user=YUhXLEoAAAAJ&hl=en"
  impactstory:
  orcid: "https://orcid.org/0009-0001-8938-7437"
  semantic:
  pubmed:
  researchgate:
  scopus:

  bitbucket:
  codepen:
  dribbble:
  github: "shangzongjiang"
  kaggle:
  stackoverflow:

  bluesky:
  facebook:
  flickr:
  foursquare:
  goodreads:
  google_plus:
  keybase:
  instagram:
  lastfm:
  linkedin:
  mastodon:
  medium:
  pinterest:
  soundcloud:
  steam:
  telegram:
  tumblr:
  twitter:
  vine:
  weibo:
  wikipedia:
  xing:
  youtube:
  zhihu:
